from pathlib import Path
from type_aliases import Pathlike
from typing import Dict, Iterator, Optional

def get_data(
        url: str,
        headers: Optional[Dict[str, str]]=...
) -> Iterator[bytes]: ...

def get_html(url: str, headers: Optional[Dict[str, str]]=...) -> str: ...

def resolve_filename_clash(fname: Pathlike) -> Path: ...

def download(
        url: str,
        fname: Pathlike,
        headers: Optional[Dict[str, str]]=...,
        force: bool=...
) -> Path: ...
