# Stubs for download (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Dict, Iterator, Optional

def get_data(
        url: str,
        headers: Optional[Dict[str, str]] = ...
) -> Iterator[bytes]: ...

def get_html(url: str, headers: Optional[Dict[str, str]] = ...) -> str: ...

def resolve_filename_clash(fname: str) -> str: ...

def download(
        url: str,
        fname: str,
        headers: Optional[Dict[str, str]] = ...,
        force: bool = ...
) -> str: ...
