from typing import TypeVar, Type
from type_aliases import Function

C = TypeVar('C')

def export(func: Function) -> Function: ...
def cls_export(func: Function) -> Function: ...
def collect_exports(cls: Type[C]) -> Type[C]: ...
